version: '2.4'

services:

    fail2ban:
        image: stlouisn/fail2ban:latest
        container_name: fail2ban
        hostname: fail2ban
        environment:
            - LC_ALL=C.UTF-8
            - TZ=America/Halifax
        restart: unless-stopped
#         volumes:
#             - 
#         cap_add:
#             - 
#         sysctls:
#             - 
        logging:
            driver: json-file
            options:
                max-size: "10M"
                max-file: "3"
#         healthcheck:
